// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SilverbackApi.Data;

#nullable disable

namespace SilverbackApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SilverbackApi.Domain.Models.AdminHistorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OcurrioEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MiembroId");

                    b.ToTable("AdminHistorial");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.AliadoComercial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlBase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AliadosComerciales");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.BeneficioAliado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AliadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RangoMinimo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AliadoId");

                    b.ToTable("BeneficiosAliado");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Clan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadMiembros")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LiderClanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PuntosClan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Clanes");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Cofre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ObtendioEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rareza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MiembroId");

                    b.ToTable("Cofres");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.DatosBiometricos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AlturaCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NivelExperiencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("MiembroId")
                        .IsUnique();

                    b.ToTable("DatosBiometricos");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.DatosFatiga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CargaSemanal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NivelFatiga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MiembroId")
                        .IsUnique();

                    b.ToTable("DatosFatiga");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.DesafioClan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecompensaXp")
                        .HasColumnType("int");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.ToTable("DesafiosClan");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Entrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ejercicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("PuntajeCer")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiembroId");

                    b.ToTable("Entrenamientos");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.GuerraGlobal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Semana")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Semana")
                        .IsUnique();

                    b.ToTable("GuerrasGlobales");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.InventarioItem", b =>
                {
                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompradoEn")
                        .HasColumnType("datetime2");

                    b.HasKey("MiembroId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("InventarioItems");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.InversionNodo", b =>
                {
                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NodoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InvertidoEn")
                        .HasColumnType("datetime2");

                    b.HasKey("MiembroId", "NodoId");

                    b.HasIndex("NodoId");

                    b.ToTable("InversionesNodo");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.MensajeClan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnviadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("MiembroId");

                    b.ToTable("MensajesClan");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Miembro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Arquetipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("OnboardingCompletado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rango")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Miembros");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Nodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CostoXp")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nodos");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.NodoDependencia", b =>
                {
                    b.Property<Guid>("NodoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrerequisiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NodoId", "PrerequisiteId");

                    b.HasIndex("PrerequisiteId");

                    b.ToTable("NodoDependencias");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.ParticipacionGuerra", b =>
                {
                    b.Property<Guid>("GuerraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CerAcumulado")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.HasKey("GuerraId", "ClanId");

                    b.HasIndex("ClanId");

                    b.ToTable("ParticipacionesGuerra");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Racha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DiasConsecutivos")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UltimoEntrenamiento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MiembroId")
                        .IsUnique();

                    b.ToTable("Rachas");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.ReclamoBeneficio", b =>
                {
                    b.Property<Guid>("BeneficioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReclamadoEn")
                        .HasColumnType("datetime2");

                    b.HasKey("BeneficioId", "MiembroId");

                    b.HasIndex("MiembroId");

                    b.ToTable("ReclamosBeneficio");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Trofeo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ObtendioEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MiembroId");

                    b.ToTable("Trofeos");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.AdminHistorial", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Miembro", "Miembro")
                        .WithMany("HistorialAdmin")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.BeneficioAliado", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.AliadoComercial", "Aliado")
                        .WithMany("Beneficios")
                        .HasForeignKey("AliadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aliado");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Cofre", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Miembro", "Miembro")
                        .WithMany("Cofres")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.DatosBiometricos", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Miembro", "Miembro")
                        .WithOne("DatosBiometricos")
                        .HasForeignKey("SilverbackApi.Domain.Models.DatosBiometricos", "MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.DatosFatiga", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Miembro", "Miembro")
                        .WithOne("DatosFatiga")
                        .HasForeignKey("SilverbackApi.Domain.Models.DatosFatiga", "MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.DesafioClan", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Clan", "Clan")
                        .WithMany("Desafios")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Entrenamiento", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Miembro", "Miembro")
                        .WithMany("Entrenamientos")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.InventarioItem", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Item", "Item")
                        .WithMany("Inventarios")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SilverbackApi.Domain.Models.Miembro", "Miembro")
                        .WithMany("InventarioItems")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.InversionNodo", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Miembro", "Miembro")
                        .WithMany("InversionesNodo")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SilverbackApi.Domain.Models.Nodo", "Nodo")
                        .WithMany("Inversiones")
                        .HasForeignKey("NodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");

                    b.Navigation("Nodo");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.MensajeClan", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Clan", "Clan")
                        .WithMany("Mensajes")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SilverbackApi.Domain.Models.Miembro", "Miembro")
                        .WithMany("MensajesClan")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Miembro", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Clan", "Clan")
                        .WithMany("Miembros")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.NodoDependencia", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Nodo", "Nodo")
                        .WithMany("Requiere")
                        .HasForeignKey("NodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SilverbackApi.Domain.Models.Nodo", "Prerequisito")
                        .WithMany("RequeridoPor")
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nodo");

                    b.Navigation("Prerequisito");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.ParticipacionGuerra", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Clan", "Clan")
                        .WithMany("Participaciones")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SilverbackApi.Domain.Models.GuerraGlobal", "Guerra")
                        .WithMany("Participaciones")
                        .HasForeignKey("GuerraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");

                    b.Navigation("Guerra");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Racha", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Miembro", "Miembro")
                        .WithOne("Racha")
                        .HasForeignKey("SilverbackApi.Domain.Models.Racha", "MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.ReclamoBeneficio", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.BeneficioAliado", "Beneficio")
                        .WithMany("Reclamos")
                        .HasForeignKey("BeneficioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SilverbackApi.Domain.Models.Miembro", "Miembro")
                        .WithMany("ReclamosBeneficio")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficio");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Trofeo", b =>
                {
                    b.HasOne("SilverbackApi.Domain.Models.Miembro", "Miembro")
                        .WithMany("Trofeos")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.AliadoComercial", b =>
                {
                    b.Navigation("Beneficios");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.BeneficioAliado", b =>
                {
                    b.Navigation("Reclamos");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Clan", b =>
                {
                    b.Navigation("Desafios");

                    b.Navigation("Mensajes");

                    b.Navigation("Miembros");

                    b.Navigation("Participaciones");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.GuerraGlobal", b =>
                {
                    b.Navigation("Participaciones");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Item", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Miembro", b =>
                {
                    b.Navigation("Cofres");

                    b.Navigation("DatosBiometricos");

                    b.Navigation("DatosFatiga");

                    b.Navigation("Entrenamientos");

                    b.Navigation("HistorialAdmin");

                    b.Navigation("InventarioItems");

                    b.Navigation("InversionesNodo");

                    b.Navigation("MensajesClan");

                    b.Navigation("Racha");

                    b.Navigation("ReclamosBeneficio");

                    b.Navigation("Trofeos");
                });

            modelBuilder.Entity("SilverbackApi.Domain.Models.Nodo", b =>
                {
                    b.Navigation("Inversiones");

                    b.Navigation("RequeridoPor");

                    b.Navigation("Requiere");
                });
#pragma warning restore 612, 618
        }
    }
}
